baseURL: 'https://products.fardog.io/'
languageCode: 'en-us'
title: 'Products'
theme: ananke

taxonomies:
  categories: categories
  tag: tags
  origin: origin
  nationality: nationality

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 50
enableRobotsTXT: true
