baseURL: "https://madewhere.co"
title: "madewhere"
copyright: madewhere Contributors

theme: ananke

sectionPagesMenu: main
paginate: 50
enableRobotsTXT: true

defaultContentLanguage: en
languages:
  en:
    languageCode: "en-US"

taxonomies:
  category: categories
  tag: tags
  origin: origins

related:
  includeNewer: true
  indices:
    - name: parent
      weight: 100
  threshold: 80
  toLower: true

params:
  repository:
    text: github.com/madewhere/madewhere.co
    url: https://github.com/madewhere/madewhere.co
  contributing:
    text: Contribution Guide
    url: https://github.com/madewhere/madewhere.co/blob/main/CONTRIBUTING.md
  contentLicense:
    text: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  codeLicense:
    text: MIT
    url: https://github.com/madewhere/madewhere.co/blob/main/LICENSE
  codeOfConduct:
    text: Contributor Covenant Code of Conduct
    url: https://github.com/madewhere/madewhere.co/blob/main/CODE_OF_CONDUCT.md
