name: Update Meta
description: Update site content not related to a brand or vendor.
labels:
  - enhancement
title: "[Update Meta]: "
assignees:
  - fardog
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an issue about madewhere's content! This section
        contains instructions on how to fill out this template.

        In order to ensure your request is handled efficiently and without too much
        back-and-forth, please be sure to fill out each question as completely as you
        can. If you don't, we may request more information or close the issue as being
        un-actionable.

        Keep in mind that we have a [Code of Conduct we expect you to abide by when
        interacting with this project. You can read it at:
        https://github.com/madewhere/madewhere.co/blob/main/CODE_OF_CONDUCT.md

        Also understand that any content you provide will be licensed under a creative
        commons license; you may read more about it here:
        https://creativecommons.org/licenses/by/4.0/
        Thanks again!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: entity_url
    attributes:
      label: Page URL
      description: Paste a URL to the existing page
      placeholder: ex. "https://madewhere.co/about"
    validations:
      required: true
  - type: checkboxes
    id: license
    attributes:
      label: Licensing
      description: Content on this site is [Creative Commons](https://creativecommons.org/licenses/by/4.0/) licensed; any content you provide will be licensed under those terms.
      options:
        - label: I agree to licensing this content under the Creative Commons Attribution 4.0 license
          required: true
  - type: textarea
    id: content
    attributes:
      label: Content
      description: What needs to change, and why?
